name: IPTV 列表更新器

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 UTC 时间 21:00 运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install "dnspython==2.3.0"  # 关键修改：固定 dnspython 版本
          pip install \
            "requests==2.31.0" \
            "urllib3==1.26.0" \
            "eventlet==0.33.0" \
            "selenium==4.10.0"

      - name: 运行扫描脚本
        run: |
          ls -la
          python iptv_scanner.py
          head -n 5 ip.txt tvlist.txt || echo "文件不存在"

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ip.txt tvlist.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "自动更新IPTV列表 [skip ci]"
            git pull --rebase
            git push
          fi
