name: IPTV List Updater

on:
  schedule:
    - cron: '0 21 * * *'  # 每天UTC时间21:00运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 必须添加这个权限才能推送更改

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Changed from 3.12.3 to 3.11 to avoid distutils issue

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools  # Required for distutils
          pip install \
            "requests==2.31.0" \
            "urllib3==1.26.0" \
            "eventlet==0.33.0" \
            "selenium==4.10.0"

      - name: Run IPTV scanner
        run: |
          echo "当前目录内容:"
          ls -la
          python iptv_scanner.py
          echo "运行后目录内容:"
          ls -la
          echo "文件内容预览:"
          head -n 5 ip.txt tvlist.txt || echo "文件不存在"

      - name: Commit and push changes
        run: |
          # 配置Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 检查变更
          git status
          git diff
          
          # 添加并提交变更
          git add ip.txt tvlist.txt
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "自动更新IPTV列表 [skip ci]"
            git pull --rebase
            git push
            echo "变更已推送"
          else
            echo "没有变更需要提交"
          fi
